### ISSUE TITLE
countryCode returning dial code instead of ISO 1366 country code

### ISSUE THREAD

**Issue by cybex-dev** [flutter-form-builder-ecosystem/phone_number#71] opened 2022-07-16 19:18 UTC
## Environment

**Package version: 0.12.0+2** (latest on pub.dev as of July 2022)

<details>
  <summary>Flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on Arch Linux 5.18.7-arch1-1, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

<details>
  <summary>Code sample</summary>

```dart
// random US number
final hint = "+11234567890"

// parse number into PhoneNumber object
final phoneNumber = await PhoneNumberUtil().parse(hint);

// extract country code
print(phoneNumber.countryCode) // prints 1 instead of 'US' as documentation states
```

</details>

## Description
Either documentation is incorrect or function is incorrect. Documentation states [countryCode](https://github.com/flutter-form-builder-ecosystem/phone_number/blob/main/lib/src/models/phone_number.dart#L13) should return [ISO 3166-1 alpha-2](https://www.iso.org/obp/ui/#iso:pub:PUB500001:en) codes like 'US', instead it returns the country's dialcode.

Documentation states

**Expected behavior:**
`phoneNumber.countryCode` should return country code i.e. "US" or "ZA"

**Current behavior:**
`phoneNumber.countryCode` returns country's dialing code i.e. "1" or "27"

_Tested on US number and South African numbers._

**Comment by ooglek** [comment] 2022-08-01 17:43
Seconding this -- agreed!

**Comment by iamsahilsonawane** [comment] 2022-08-06 15:10
@cybex-dev @ooglek 

The issue is now been fixed in [this](https://github.com/flutter-form-builder-ecosystem/phone_number/pull/81) PR. Once it gets merged you can use:

```dart
phoneNumber.countryCode; // Ex: 1 or 27
phoneNumber.regionCode; // Ex: "US" or "ZA"
```

Sorry for the delay. Thanks for pointing out the issue!

**Closed** 2022-08-07 09:03 UTC
Labels: bug
